[project]
name = "odoo-addons-ecosoft-odoo-ecosoft-addons"
version = "18.0.20260714.0"
dependencies = [
    "odoo-addon-analytic_tag_dimension==18.0.*",
    "odoo-addon-base_hide_action_delete==18.0.*",
    "odoo-addon-base_print_wizard==18.0.*",
    "odoo-addon-base_tier_validation_multi==18.0.*",
    "odoo-addon-frappe_etax_service==18.0.*",
    "odoo-addon-frappe_etax_service_queue==18.0.*",
    "odoo-addon-request_document==18.0.*",
    "odoo-addon-request_document_exception==18.0.*",
    "odoo-addon-request_document_expense==18.0.*",
    "odoo-addon-request_document_purchase_request==18.0.*",
    "odoo-addon-request_document_tier_validation==18.0.*",
    "odoo-addon-usability_api_connector==18.0.*",
    "odoo-addon-usability_webhooks==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
